import Head from "next/head";
import Image from "next/image";
import Header from "../Components/Header";
import Navbar from "../Components/Navbar";
import Results from "../Components/Results";
import requests from "../request";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header />
      {/* nav */}
      <Navbar />
      {/* results */}
      <Results results={results.results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  console.log(genre);
  const data = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());
  console.log(data);
  return {
    props: {
      results: data,
    },
  };
}
